server:
  port: 8091
  tomcat:
    threads:
      max: 200        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# Apache ShardingSphere 分库分表配置
spring:
  shardingsphere:
    datasource:
      names: db01,db02
      db01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/big_market_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456
        hikari:
          pool-name: Retail_HikariCP_db01
          minimum-idle: 15
          idle-timeout: 180000
          maximum-pool-size: 25
          auto-commit: true
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
      db02:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/big_market_02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456
        hikari:
          pool-name: Retail_HikariCP_db02
          minimum-idle: 15
          idle-timeout: 180000
          maximum-pool-size: 25
          auto-commit: true
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
    rules:
      sharding:
        tables:
          raffle_activity_order:
            actual-data-nodes: db0${1..2}.raffle_activity_order_00${0..3}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: table-inline
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-inline
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: db0${(user_id.hashCode() & 1) + 1}
          table-inline:
            type: INLINE
            props:
              algorithm-expression: raffle_activity_order_00${user_id.hashCode() % 4}
    props:
      sql-show: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml